volumes:
  portfolio-node-modules:

services:
  portfolio-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/app:/app
      - portfolio-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - portfolio-app-network

networks:
  portfolio-app-network:
    driver: bridge